#Koneksi ke Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Membaca dan menampilkan data dari folder

In [ ]:
import pandas as pd

# Path yang benar
file_path = "/content/drive/My Drive/GOOGLE COLAB/DATA SCIENCE/QUIZ/Mata Kuliah TRPL.xlsx"

# Membaca file Excel
data = pd.read_excel(file_path)

# Menampilkan semua data
print(data)

   Kode Mata Kuliah                       Nama Mata Kuliah                                  Dosen Pengampu  Jumlah SKS  Semester Tipe Mata Kuliah Ruang Kelas Hari Perkuliahan  Jumlah Mahasiswa Waktu Perkuliahan
0           4143201                           UI/UX Design               Riyanthi Angrainy Sianturi, M.Ds.           3         6            Wajib       GD516            Senin                50     08.00 - 09.50
1           4143202                       Manajemen Proyek  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.           3         6            Wajib       GD513            Senin                60     09.00 - 09.50
2           4143203                           Data Science                  Oppir Hutapea, S.Tr.Kom, M.Kom           3         6          Pilihan       GD517            Senin                58     13.00 - 13.50
3           4143204                               Big Data                  Oppir Hutapea, S.Tr.Kom, M.Kom           2         6            Wajib       GD516           Selasa                70     10.00 - 11.50
4           4143290                 Proyek Akhir Tahun III                  Oppir Hutapea, S.Tr.Kom, M.Kom           4         6            Wajib       GD516           Selasa                50    15.00 - 16.50
5           4142203              Pengujian Perangkat Lunak  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.           3         3            Wajib       GD516            Kamis                50     13.00 - 14.50
6           4142201    Pengembangan Aplikasi Terdistribusi                  Oppir Hutapea, S.Tr.Kom, M.Kom           3         3          Pilihan       GD516            Kamis                60     09.00 - 09.50
7           4142202           Pengembangan Aplikasi Mobile             Tegar Arifin Prasetyo, S.Si., M.Si.           3         4            Wajib       GD516             Rabu                58     08.00 - 09.50
8           4141201     Analisis Kebutuhan Perangkat Lunak              Verawaty Situmorang, S.Kom., M.T.I           3         2            Wajib       GD924             Rabu                70     08.00 - 09.50
9           4141203                  Pengenalan Basis Data              Verawaty Situmorang, S.Kom., M.T.I           3         2            Wajib       GD921            Jumat                60     08.00 - 09.50
10          4142290                  Proyek Akhir Tahun II                      Ardiles Sinaga, S.T., M.T.           2         2            Wajib       GD524           Selasa                50     08.00 - 09.50
11          4141105     Arsitektur dan Organisasi Komputer                       Istas Manalu, S.Si., M.Sc           2         1          Pilihan       GD921            Jumat                60     09.00 - 09.50
12          KU41103  Penyelesaian Masalah di Dunia Digital             Eka Stephani Sinambela, SST., M.Sc.           3         1          Pilihan       GD527           Selasa                58     08.00 - 09.50
13          4141101                      Dasar Pemrograman                      Ardiles Sinaga, S.T., M.T.           3         1            Wajib       GD526            Senin                65     13.00 - 14.50
14          4141102                     Matematika Diskrit               Sari Muthia Silalahi, S.Pd., M.Ed           3         1            Wajib       GD525             Rabu                70     13.00 - 14.50
15          4141103               Pengembangan Situs Web I                  Oppir Hutapea, S.Tr.Kom, M.Kom           3         1            Wajib       GD524            Kamis                58     13.00 - 14.50
16          4141104    Pengenalan Rekayasa Perangkat Lunak              Verawaty Situmorang, S.Kom., M.T.I           2         1            Wajib       GD921            Jumat                65     08.00 - 09.50
17          KU41101                       Bahasa Inggris I         Rumondang Miranda Marsaulina, S.P, M.Si           2         1            Wajib       GD914            Jumat                58     09.00 - 09.50
18          KU41102               Pembentukan Karakter Del    Dr. Johannes Harungguan Sianipar, S.T., M.T.           3         1            Wajib       GD513            Kamis                65     08.00 - 09.50
19          4142105                      Jaringan Komputer                       Istas Manalu, S.Si., M.Sc           3         3            Wajib       GD513            Senin                58    15.00 - 16.50
20          4142101            Algoritma dan Struktur Data                      Ardiles Sinaga, S.T., M.T.           2         3            Wajib       GD527           Selasa                65     08.00 - 09.50
21          4142106           Pengenalan Kecerdasan Buatan                  Oppir Hutapea, S.Tr.Kom, M.Kom           3         4          Pilihan       GD527             Rabu                70     13.00 - 13.50
22          4142102         Perancangan Antarmuka Pengguna               Riyanthi Angrainy Sianturi, M.Ds.           3         3            Wajib       GD527             Rabu                50     08.00 - 09.50
23          4142103                      Sistem Basis Data              Verawaty Situmorang, S.Kom., M.T.I           3         4            Wajib       GD524             Rabu                65     09.00 - 09.50
24          4142107                     Logika Informatika                             Ana Muliyana, M.Pd.           2         3            Wajib       GD921            Senin                65     08.00 - 09.50
25          4142104         Pemrograman Berorientasi Objek                      Ardiles Sinaga, S.T., M.T.           3         3          Pilihan       GD516           Selasa                58    15.00 - 16.50
26          KU42101                      Bahasa Inggris II         Rumondang Miranda Marsaulina, S.P, M.Si           2         2            Wajib       GD516           Selasa                68     09.00 - 09.50
27          4144101                  Metodologi Penelitian  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.           3         8            Wajib       GD516             Rabu                70     08.00 - 09.50
28          4141204                         Sistem Operasi                       Istas Manalu, S.Si., M.Sc           3         4            Wajib       GD516            Kamis                50     13.00 - 13.50
29          4141202              Pengembangan Situs Web II                  Oppir Hutapea, S.Tr.Kom, M.Kom           3         2            Wajib       GD513           Selasa                68     08.00 - 09.50
30          4141290                   Proyek Akhir Tahun I  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.           3         2            Wajib       GD527            Jumat                68     08.00 - 09.50
31          KU41202                                  Agama              Bella Wahmilyana Asril, S.T., M.T.           2         4            Wajib       GD527            Senin                68     08.00 - 09.50
32          KU41201                       Bahasa Indonesia                    Tiurma Lumban Gaol, SP., M.P           2         4            Wajib       GD524           Selasa                70     08.00 - 09.50
33          KU42201                              Pancasila              Adrianto Prihartantyo, S.Si., M.T.           2         4            Wajib       GD722             Rabu                55     13.00 - 13.50
34          MA42201            Probabilitas dan Statistika                             Ana Muliyana, M.Pd.           3         4            Wajib       GD513           Selasa                50     09.00 - 09.50
35          TI42201                      Technopreneurship               Riyanthi Angrainy Sianturi, M.Ds.           3         7            Wajib       GD722            Kamis                70     09.00 - 09.50
36          4143101                       Algoritma Lanjut             Tegar Arifin Prasetyo, S.Si., M.Si.           3         5            Wajib       GD524            Kamis                55     13.00 - 13.50
37          4143102               Keamanan Perangkat Lunak                     Rudy Chandra, S.Kom., M.Kom           3         5          Pilihan       GD516            Jumat                50     13.00 - 13.50
38          4143103                               Automata                             Ana Muliyana, M.Pd.           3         5            Wajib       GD516            Senin                55     13.00 - 13.50
39          4143104                     Pembelajaran Mesin             Tegar Arifin Prasetyo, S.Si., M.Si.           3         5            Wajib       GD516           Selasa                50     08.00 - 09.50
40          4143105                          Data Analitik              Verawaty Situmorang, S.Kom., M.T.I           3         5            Wajib       GD516             Rabu                70     13.00 - 13.50
41          4143106               Kualitas Perangkat Lunak  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.           3         5            Wajib       GD524            Kamis                55     13.00 - 13.50
42          4143205        Tata Kelola Teknologi Informasi                     Rudy Chandra, S.Kom., M.Kom           3         3          Pilihan       GD513            Jumat                55     13.00 - 13.50
43          KU43201                     Bahasa Inggris III         Rumondang Miranda Marsaulina, S.P, M.Si           2         3            Wajib       GD513           Selasa                50     09.00 - 09.50
44          KU44202                        Kewarganegaraan              Adrianto Prihartantyo, S.Si., M.T.           2         6            Wajib       GD524            Jumat                55     08.00 - 09.50
45          KU44201                      Bahasa Inggris IV         Rumondang Miranda Marsaulina, S.P, M.Si           2         7            Wajib       GD527            Kamis                50     08.00 - 09.50
46          4144290                            Tugas Akhir                  Oppir Hutapea, S.Tr.Kom, M.Kom           6         8            Wajib       GD527            Senin                55    15.00 - 16.50

#Menampilkan tipe data

In [ ]:
print(data.dtypes)

Kode Mata Kuliah     object
Nama Mata Kuliah     object
Dosen Pengampu       object
Jumlah SKS            int64
Semester              int64
Tipe Mata Kuliah     object
Ruang Kelas          object
Hari Perkuliahan     object
Jumlah Mahasiswa      int64
Waktu Perkuliahan    object
dtype: object

#Menampilkan data yang kategorik

In [ ]:
# Menampilkan hanya kolom yang diinginkan
selected_columns = data[[ "Dosen Pengampu","Tipe Mata Kuliah", "Ruang Kelas", "Hari Perkuliahan", "Waktu Perkuliahan"]]

# Menampilkan hasil
print(selected_columns)

                                    Dosen Pengampu Tipe Mata Kuliah Ruang Kelas Hari Perkuliahan Waktu Perkuliahan
0                Riyanthi Angrainy Sianturi, M.Ds.            Wajib       GD516            Senin     08.00 - 09.50
1   Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.            Wajib       GD513            Senin     09.00 - 09.50
2                   Oppir Hutapea, S.Tr.Kom, M.Kom          Pilihan       GD517            Senin     13.00 - 13.50
3                   Oppir Hutapea, S.Tr.Kom, M.Kom            Wajib       GD516           Selasa     10.00 - 11.50
4                   Oppir Hutapea, S.Tr.Kom, M.Kom            Wajib       GD516           Selasa    15.00 - 16.50
5   Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.            Wajib       GD516            Kamis     13.00 - 14.50
6                   Oppir Hutapea, S.Tr.Kom, M.Kom          Pilihan       GD516            Kamis     09.00 - 09.50
7              Tegar Arifin Prasetyo, S.Si., M.Si.            Wajib       GD516             Rabu     08.00 - 09.50
8               Verawaty Situmorang, S.Kom., M.T.I            Wajib       GD924             Rabu     08.00 - 09.50
9               Verawaty Situmorang, S.Kom., M.T.I            Wajib       GD921            Jumat     08.00 - 09.50
10                      Ardiles Sinaga, S.T., M.T.            Wajib       GD524           Selasa     08.00 - 09.50
11                       Istas Manalu, S.Si., M.Sc          Pilihan       GD921            Jumat     09.00 - 09.50
12             Eka Stephani Sinambela, SST., M.Sc.          Pilihan       GD527           Selasa     08.00 - 09.50
13                      Ardiles Sinaga, S.T., M.T.            Wajib       GD526            Senin     13.00 - 14.50
14               Sari Muthia Silalahi, S.Pd., M.Ed            Wajib       GD525             Rabu     13.00 - 14.50
15                  Oppir Hutapea, S.Tr.Kom, M.Kom            Wajib       GD524            Kamis     13.00 - 14.50
16              Verawaty Situmorang, S.Kom., M.T.I            Wajib       GD921            Jumat     08.00 - 09.50
17         Rumondang Miranda Marsaulina, S.P, M.Si            Wajib       GD914            Jumat     09.00 - 09.50
18    Dr. Johannes Harungguan Sianipar, S.T., M.T.            Wajib       GD513            Kamis     08.00 - 09.50
19                       Istas Manalu, S.Si., M.Sc            Wajib       GD513            Senin    15.00 - 16.50
20                      Ardiles Sinaga, S.T., M.T.            Wajib       GD527           Selasa     08.00 - 09.50
21                  Oppir Hutapea, S.Tr.Kom, M.Kom          Pilihan       GD527             Rabu     13.00 - 13.50
22               Riyanthi Angrainy Sianturi, M.Ds.            Wajib       GD527             Rabu     08.00 - 09.50
23              Verawaty Situmorang, S.Kom., M.T.I            Wajib       GD524             Rabu     09.00 - 09.50
24                             Ana Muliyana, M.Pd.            Wajib       GD921            Senin     08.00 - 09.50
25                      Ardiles Sinaga, S.T., M.T.          Pilihan       GD516           Selasa    15.00 - 16.50
26         Rumondang Miranda Marsaulina, S.P, M.Si            Wajib       GD516           Selasa     09.00 - 09.50
27  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.            Wajib       GD516             Rabu     08.00 - 09.50
28                       Istas Manalu, S.Si., M.Sc            Wajib       GD516            Kamis     13.00 - 13.50
29                  Oppir Hutapea, S.Tr.Kom, M.Kom            Wajib       GD513           Selasa     08.00 - 09.50
30  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.            Wajib       GD527            Jumat     08.00 - 09.50
31              Bella Wahmilyana Asril, S.T., M.T.            Wajib       GD527            Senin     08.00 - 09.50
32                    Tiurma Lumban Gaol, SP., M.P            Wajib       GD524           Selasa     08.00 - 09.50
33              Adrianto Prihartantyo, S.Si., M.T.            Wajib       GD722             Rabu     13.00 - 13.50
34                             Ana Muliyana, M.Pd.            Wajib       GD513           Selasa     09.00 - 09.50
35               Riyanthi Angrainy Sianturi, M.Ds.            Wajib       GD722            Kamis     09.00 - 09.50
36             Tegar Arifin Prasetyo, S.Si., M.Si.            Wajib       GD524            Kamis     13.00 - 13.50
37                     Rudy Chandra, S.Kom., M.Kom          Pilihan       GD516            Jumat     13.00 - 13.50
38                             Ana Muliyana, M.Pd.            Wajib       GD516            Senin     13.00 - 13.50
39             Tegar Arifin Prasetyo, S.Si., M.Si.            Wajib       GD516           Selasa     08.00 - 09.50
40              Verawaty Situmorang, S.Kom., M.T.I            Wajib       GD516             Rabu     13.00 - 13.50
41  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.            Wajib       GD524            Kamis     13.00 - 13.50
42                     Rudy Chandra, S.Kom., M.Kom          Pilihan       GD513            Jumat     13.00 - 13.50
43         Rumondang Miranda Marsaulina, S.P, M.Si            Wajib       GD513           Selasa     09.00 - 09.50
44              Adrianto Prihartantyo, S.Si., M.T.            Wajib       GD524            Jumat     08.00 - 09.50
45         Rumondang Miranda Marsaulina, S.P, M.Si            Wajib       GD527            Kamis     08.00 - 09.50
46                  Oppir Hutapea, S.Tr.Kom, M.Kom            Wajib       GD527            Senin    15.00 - 16.50

#Menampilkan total setiap data kategori

In [ ]:
# Mengubah beberapa kolom menjadi tipe kategori
columns_to_convert = ["Dosen Pengampu", "Tipe Mata Kuliah", "Ruang Kelas", "Hari Perkuliahan", "Waktu Perkuliahan"]
data[columns_to_convert] = data[columns_to_convert].astype('category')

# Menampilkan jumlah kategori untuk setiap kolom
jumlah_kategori_per_kolom = data[columns_to_convert].nunique()
print(jumlah_kategori_per_kolom)

# Menghitung total kategori unik di semua kolom
total_kategori = jumlah_kategori_per_kolom.sum()
print(f"\nTotal kategori unik di semua kolom: {total_kategori}")

Dosen Pengampu       16
Tipe Mata Kuliah      2
Ruang Kelas          11
Hari Perkuliahan      5
Waktu Perkuliahan     6
dtype: int64

Total kategori unik di semua kolom: 40

#Menampilkan daftar kategori dan jumlah datanya

In [ ]:
# Menampilkan daftar kategori dan jumlah datanya untuk setiap kolom
for col in columns_to_convert:
    print(f"\n{col}:")
    print(data[col].value_counts())  # Menampilkan kategori beserta jumlahnya

Dosen Pengampu:
Dosen Pengampu
Oppir Hutapea, S.Tr.Kom, M.Kom                    8
Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.    5
Verawaty Situmorang, S.Kom., M.T.I                5
Ardiles Sinaga, S.T., M.T.                        4
Rumondang Miranda Marsaulina, S.P, M.Si           4
Ana Muliyana, M.Pd.                               3
Istas Manalu, S.Si., M.Sc                         3
Riyanthi Angrainy Sianturi, M.Ds.                 3
Tegar Arifin Prasetyo, S.Si., M.Si.               3
Adrianto Prihartantyo, S.Si., M.T.                2
Rudy Chandra, S.Kom., M.Kom                       2
Bella Wahmilyana Asril, S.T., M.T.                1
Dr. Johannes Harungguan Sianipar, S.T., M.T.      1
Eka Stephani Sinambela, SST., M.Sc.               1
Sari Muthia Silalahi, S.Pd., M.Ed                 1
Tiurma Lumban Gaol, SP., M.P                      1
Name: count, dtype: int64

Tipe Mata Kuliah:
Tipe Mata Kuliah
Wajib      39
Pilihan     8
Name: count, dtype: int64

Ruang Kelas:
Ruang Kelas
GD516    14
GD527     8
GD513     7
GD524     7
GD921     4
GD722     2
GD517     1
GD525     1
GD526     1
GD914     1
GD924     1
Name: count, dtype: int64

Hari Perkuliahan:
Hari Perkuliahan
Selasa    12
Kamis      9
Rabu       9
Senin      9
Jumat      8
Name: count, dtype: int64

Waktu Perkuliahan:
Waktu Perkuliahan
08.00 - 09.50     19
13.00 - 13.50     10
09.00 - 09.50      9
13.00 - 14.50      4
15.00 - 16.50      4
10.00 - 11.50      1
Name: count, dtype: int64

#Konversi Kategori dengan Mapping Manual dan Randomization

In [ ]:
import pandas as pd
import random

# Mapping kolom
mapping_dosen = {
    "Adrianto Prihartantyo, S.Si., M.T.": 0,
    "Ana Muliyana, M.Pd.": 1,
    "Ardiles Sinaga, S.T., M.T.": 2,
    "Bella Wahmilyana Asril, S.T., M.T.": 3,
    "Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.": 4,
    "Dr. Johannes Harungguan Sianipar, S.T., M.T.": 5,
    "Eka Stephani Sinambela, SST., M.Sc.": 6,
    "Istas Manalu, S.Si., M.Sc": 7,
    "Oppir Hutapea, S.Tr.Kom, M.Kom": 8,
    "Riyanthi Angrainy Sianturi, M.Ds.": 9,
    "Rudy Chandra, S.Kom., M.Kom": 10,
    "Rumondang Miranda Marsaulina, S.P, M.Si": 11,
    "Sari Muthia Silalahi, S.Pd., M.Ed": 12,
    "Tegar Arifin Prasetyo, S.Si., M.Si.": 13,
    "Tiurma Lumban Gaol, SP., M.P": 14,
    "Verawaty Situmorang, S.Kom., M.T.I": 15
}

mapping_tipe_mk = {"Pilihan": 0, "Wajib": 1}

mapping_ruang_kelas = {
    "GD513": 0, "GD516": 1, "GD517": 2, "GD524": 3, "GD525": 4,
    "GD526": 5, "GD527": 6, "GD722": 7, "GD914": 8, "GD921": 9, "GD924": 10
}

mapping_hari = {"Jumat": 0, "Kamis": 1, "Rabu": 2, "Selasa": 3, "Senin": 4}

mapping_waktu = {
    "03.00 - 14.50": 0, "08.00 - 09.50": 1, "10.00 - 11.50": 2,
    "15.00 - 16.50": 3, "19.00 - 19.50": 4
}

# Daftar dosen berdasarkan urutan mapping
dosen_list = list(mapping_dosen.keys())

# Menentukan jumlah data berdasarkan jumlah dosen
jumlah_data = len(dosen_list)

# Membuat DataFrame dengan data yang diacak
data = {
    "Dosen Pengampu": [mapping_dosen[d] for d in dosen_list],  # Sesuai urutan mapping
    "Tipe Mata Kuliah": [mapping_tipe_mk[random.choice(list(mapping_tipe_mk.keys()))] for _ in range(jumlah_data)],
    "Ruang Kelas": [mapping_ruang_kelas[random.choice(list(mapping_ruang_kelas.keys()))] for _ in range(jumlah_data)],
    "Hari Perkuliahan": [mapping_hari[random.choice(list(mapping_hari.keys()))] for _ in range(jumlah_data)],
    "Waktu Perkuliahan": [mapping_waktu[random.choice(list(mapping_waktu.keys()))] for _ in range(jumlah_data)]
}

df = pd.DataFrame(data)

# Menampilkan DataFrame
print(df)

    Dosen Pengampu  Tipe Mata Kuliah  Ruang Kelas  Hari Perkuliahan  Waktu Perkuliahan
0                0                 0            0                 1                  4
1                1                 1            7                 1                  2
2                2                 1            1                 0                  0
3                3                 0            8                 4                  1
4                4                 1            8                 3                  1
5                5                 0            3                 4                  4
6                6                 1            6                 1                  0
7                7                 1            5                 4                  3
8                8                 0            0                 0                  4
9                9                 1            6                 1                  2
10              10                 1            3                 0                  1
11              11                 1            9                 0                  4
12              12                 1            0                 1                  2
13              13                 1            8                 0                  1
14              14                 1            7                 0                  3
15              15                 1            8                 1                  0

#Encoding Otomatis dengan LabelEncoder

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Data kategori
data = {
    "Dosen Pengampu": [
        "Oppir Hutapea, S.Tr.Kom, M.Kom",
        "Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.",
        "Verawaty Situmorang, S.Kom., M.T.I",
        "Ardiles Sinaga, S.T., M.T.",
        "Rumondang Miranda Marsaulina, S.P, M.Si",
        "Ana Muliyana, M.Pd.",
        "Istas Manalu, S.Si., M.Sc",
        "Riyanthi Angrainy Sianturi, M.Ds.",
        "Tegar Arifin Prasetyo, S.Si., M.Si.",
        "Adrianto Prihartantyo, S.Si., M.T.",
        "Rudy Chandra, S.Kom., M.Kom",
        "Bella Wahmilyana Asril, S.T., M.T.",
        "Dr. Johannes Harungguan Sianipar, S.T., M.T.",
        "Eka Stephani Sinambela, SST., M.Sc.",
        "Sari Muthia Silalahi, S.Pd., M.Ed",
        "Tiurma Lumban Gaol, SP., M.P"
    ],

    "Tipe Mata Kuliah": [
        "Wajib", "Pilihan"
    ] * 8,  # Supaya panjangnya sama dengan jumlah dosen

    "Ruang Kelas": [
        "GD516", "GD527", "GD513", "GD524", "GD921",
        "GD722", "GD517", "GD525", "GD526", "GD914",
        "GD924", "GD516", "GD527", "GD513", "GD524", "GD921"
    ],

    "Hari Perkuliahan": [
        "Selasa", "Kamis", "Rabu", "Senin", "Jumat",
        "Selasa", "Kamis", "Rabu", "Senin", "Jumat",
        "Selasa", "Kamis", "Rabu", "Senin", "Jumat", "Senin"
    ],

    "Waktu Perkuliahan": [
        "08.00 - 09.50", "19.00 - 19.50", "03.00 - 14.50",
        "15.00 - 16.50", "10.00 - 11.50", "08.00 - 09.50",
        "19.00 - 19.50", "03.00 - 14.50", "15.00 - 16.50",
        "10.00 - 11.50", "08.00 - 09.50", "19.00 - 19.50",
        "03.00 - 14.50", "15.00 - 16.50", "10.00 - 11.50",
        "08.00 - 09.50"
    ]
}

# Membuat DataFrame
df = pd.DataFrame(data)

# Inisialisasi Label Encoder
label_encoders = {}
for column in df.columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

# Menampilkan DataFrame yang telah dikonversi ke numerik
df

    Dosen Pengampu  Tipe Mata Kuliah  Ruang Kelas  Hari Perkuliahan  Waktu Perkuliahan
0                8                 1            1                 3                  1
1                4                 0            6                 1                  4
2               15                 1            0                 2                  0
3                2                 0            3                 4                  3
4               11                 1            9                 0                  2
5                1                 0            7                 3                  1
6                7                 1            2                 1                  4
7                9                 0            4                 2                  0
8               13                 1            5                 4                  3
9                0                 0            8                 0                  2
10              10                 1           10                 3                  1
11               3                 0            1                 1                  4
12               5                 1            6                 2                  0
13               6                 0            0                 4                  3
14              12                 1            3                 0                  2
15              14                 0            9                 4                  1

#Menampilkan mapping numerik ke nilai asli setiap kolom

In [ ]:
# Menampilkan mapping numerik ke nilai asli untuk setiap kolom
for column, le in label_encoders.items():
    mapping = dict(zip(le.transform(le.classes_), le.classes_))
    print(f"Mapping untuk kolom '{column}':")
    for key, value in mapping.items():
        print(f"{key} -> {value}")
    print("\n")

Mapping untuk kolom 'Dosen Pengampu':
0 -> Adrianto Prihartantyo, S.Si., M.T.
1 -> Ana Muliyana, M.Pd.
2 -> Ardiles Sinaga, S.T., M.T.
3 -> Bella Wahmilyana Asril, S.T., M.T.
4 -> Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.
5 -> Dr. Johannes Harungguan Sianipar, S.T., M.T.
6 -> Eka Stephani Sinambela, SST., M.Sc.
7 -> Istas Manalu, S.Si., M.Sc
8 -> Oppir Hutapea, S.Tr.Kom, M.Kom
9 -> Riyanthi Angrainy Sianturi, M.Ds.
10 -> Rudy Chandra, S.Kom., M.Kom
11 -> Rumondang Miranda Marsaulina, S.P, M.Si
12 -> Sari Muthia Silalahi, S.Pd., M.Ed
13 -> Tegar Arifin Prasetyo, S.Si., M.Si.
14 -> Tiurma Lumban Gaol, SP., M.P
15 -> Verawaty Situmorang, S.Kom., M.T.I


Mapping untuk kolom 'Tipe Mata Kuliah':
0 -> Pilihan
1 -> Wajib


Mapping untuk kolom 'Ruang Kelas':
0 -> GD513
1 -> GD516
2 -> GD517
3 -> GD524
4 -> GD525
5 -> GD526
6 -> GD527
7 -> GD722
8 -> GD914
9 -> GD921
10 -> GD924


Mapping untuk kolom 'Hari Perkuliahan':
0 -> Jumat
1 -> Kamis
2 -> Rabu
3 -> Selasa
4 -> Senin


Mapping untuk kolom 'Waktu Perkuliahan':
0 -> 03.00 - 14.50
1 -> 08.00 - 09.50
2 -> 10.00 - 11.50
3 -> 15.00 - 16.50
4 -> 19.00 - 19.50

#Menampilkan mapping numerik ke nilai asli setiap kolom

In [ ]:
# Menampilkan mapping numerik ke nilai asli untuk setiap kolom
for column, le in label_encoders.items():
    mapping = dict(zip(le.transform(le.classes_), le.classes_))
    print(f"Mapping untuk kolom '{column}':")
    for key, value in mapping.items():
        print(f"{key} -> {value}")
    print("\n")

Mapping untuk kolom 'Dosen Pengampu':
0 -> Adrianto Prihartantyo, S.Si., M.T.
1 -> Ana Muliyana, M.Pd.
2 -> Ardiles Sinaga, S.T., M.T.
3 -> Bella Wahmilyana Asril, S.T., M.T.
4 -> Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.
5 -> Dr. Johannes Harungguan Sianipar, S.T., M.T.
6 -> Eka Stephani Sinambela, SST., M.Sc.
7 -> Istas Manalu, S.Si., M.Sc
8 -> Oppir Hutapea, S.Tr.Kom, M.Kom
9 -> Riyanthi Angrainy Sianturi, M.Ds.
10 -> Rudy Chandra, S.Kom., M.Kom
11 -> Rumondang Miranda Marsaulina, S.P, M.Si
12 -> Sari Muthia Silalahi, S.Pd., M.Ed
13 -> Tegar Arifin Prasetyo, S.Si., M.Si.
14 -> Tiurma Lumban Gaol, SP., M.P
15 -> Verawaty Situmorang, S.Kom., M.T.I


Mapping untuk kolom 'Tipe Mata Kuliah':
0 -> Pilihan
1 -> Wajib


Mapping untuk kolom 'Ruang Kelas':
0 -> GD513
1 -> GD516
2 -> GD517
3 -> GD524
4 -> GD525
5 -> GD526
6 -> GD527
7 -> GD722
8 -> GD914
9 -> GD921
10 -> GD924


Mapping untuk kolom 'Hari Perkuliahan':
0 -> Jumat
1 -> Kamis
2 -> Rabu
3 -> Selasa
4 -> Senin


Mapping untuk kolom 'Waktu Perkuliahan':
0 -> 03.00 - 14.50
1 -> 08.00 - 09.50
2 -> 10.00 - 11.50
3 -> 15.00 - 16.50
4 -> 19.00 - 19.50

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Data numerik
numerical_data = {
    'Kode Mata Kuliah': [4143201, 4143202, 4143203, 4143204],
    'Nama Mata Kuliah': ["Algoritma", "Struktur Data", "Machine Learning", "PBO"],
    'Jumlah SKS': [3, 3, 3, 2],
    'Semester': [6, 6, 6, 6],
    'Jumlah Mahasiswa': [50, 60, 58, 70]
}

# Data kategorik
categorical_data = {
    "Dosen Pengampu": [
        "Oppir Hutapea, S.Tr.Kom, M.Kom",
        "Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.",
        "Riyanthi Angrainy Sianturi, M.Ds.",
        "Oppir Hutapea, S.Tr.Kom, M.Kom"
    ],
    "Tipe Mata Kuliah": [
        "Wajib", "Pilihan", "Wajib", "Pilihan"
    ],
    "Ruang Kelas": [
        "GD516", "GD517", "GD513", "GD516"
    ],
    "Hari Perkuliahan": [
        "Selasa", "Senin", "Senin", "Selasa"
    ],
    "Waktu Perkuliahan": [
        "08.00 - 09.50", "10.00 - 11.50", "09.00 - 09.50", "08.00 - 09.50"
    ]
}

# Membuat DataFrame
df_numerical = pd.DataFrame(numerical_data)
df_categorical = pd.DataFrame(categorical_data)

# One-hot encoding untuk data kategorik
encoder = OneHotEncoder()
encoded_categorical = encoder.fit_transform(df_categorical).toarray()

# Membuat DataFrame dari hasil encoding dengan nama kolom yang lebih rapi
feature_names = encoder.get_feature_names_out(df_categorical.columns)

# Fungsi untuk merapikan nama kolom (menghapus prefiks kategori)
def clean_column_names(names):
    return [name.split('_')[1] for name in names]

cleaned_feature_names = clean_column_names(feature_names)
encoded_df = pd.DataFrame(encoded_categorical, columns=cleaned_feature_names)

# Menggabungkan data numerik dan hasil encoding kategorik
final_df = pd.concat([df_numerical, encoded_df], axis=1)

# Menampilkan hasil akhir
print(final_df)

   Kode Mata Kuliah  Nama Mata Kuliah  Jumlah SKS  Semester  Jumlah Mahasiswa  Dr. Arnaldo Marulitua Sinaga, ST., M.InfoTech.  Oppir Hutapea, S.Tr.Kom, M.Kom  Riyanthi Angrainy Sianturi, M.Ds.  Pilihan  Wajib  GD513  GD516  GD517  Selasa  Senin  08.00 - 09.50  09.00 - 09.50  10.00 - 11.50
0           4143201         Algoritma           3         6                50                                             0.0                             1.0                                0.0      0.0    1.0    0.0    1.0    0.0     1.0    0.0            1.0            0.0            0.0
1           4143202     Struktur Data           3         6                60                                             1.0                             0.0                                0.0      1.0    0.0    0.0    0.0    1.0     0.0    1.0            0.0            0.0            1.0
2           4143203  Machine Learning           3         6                58                                             0.0                             0.0                                1.0      0.0    1.0    1.0    0.0    0.0     0.0    1.0            0.0            1.0            0.0
3           4143204               PBO           2         6                70                                             0.0                             1.0                                0.0      1.0    0.0    0.0    1.0    0.0     1.0    0.0            1.0            0.0            0.0